language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    - secure: MONGO_URL=mongodb+srv://kevin:kevin@cluster0.llrvf.mongodb.net/Cluster0?retryWrites=true&w=majority